<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;

class DashboardsController extends AppController
{
    public function beforeFilter(Event $event)
    {
//        parent::beforeFilter($event); // TODO: Change the autogenerated stub
//        $this->Auth->allow();
    }

    public function index()
    {
        $this->viewBuilder()->setLayout('default');

//        $role = $this->Auth->user('role');
//        $this->set("roleUser",$role);
        $this->set("menuActive","#id_dash");
    }
}